# Generated by Django 3.2.25 on 2024-03-08 13:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='email')),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='wallet')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price of product')),
                ('product_category', models.CharField(max_length=100, null=True, verbose_name='list of Catergories')),
                ('image', models.ImageField(null=True, upload_to='post_images', verbose_name='image')),
                ('product_desc', models.CharField(max_length=100, null=True, verbose_name='product description')),
            ],
        ),
        migrations.CreateModel(
            name='Vtu_transaction',
            fields=[
                ('vtu_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=100, null=True, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='amout')),
                ('ref_id', models.CharField(max_length=100, verbose_name='reference number')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='phone number credited')),
                ('transaction_time', models.CharField(max_length=100, null=True, verbose_name='transaction time')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vtu_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_order', models.CharField(max_length=1000, null=True, verbose_name='Cart Item')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price of product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=1000, null=True, verbose_name='Cart Item')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankTansfer',
            fields=[
                ('tranaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=100, null=True, verbose_name='transaction type')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('sender', models.CharField(max_length=100, verbose_name='sender')),
                ('transaction_amount', models.CharField(max_length=100, verbose_name='tranaction amount')),
                ('transaction_time', models.DateTimeField(auto_now_add=True, verbose_name='date transacted')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
