# Generated by Django 3.2.25 on 2024-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
