# Generated by Django 3.2.25 on 2024-04-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(max_length=1000, null=True, verbose_name='Cart Item'),
        ),
    ]
